name: untitled
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  easy_refresh: ^3.3.2+2
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.3.3
  cupertino_icons: ^1.0.2
  getwidget: ^4.0.0
  syncfusion_flutter_charts: ^25.2.7
  sqflite: ^2.3.3+1
  path:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner-bg.jpg
