name: untitled
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  easy_refresh: ^3.3.2+2
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.3.3
  cupertino_icons: ^1.0.2
  getwidget: ^4.0.0
  syncfusion_flutter_charts: ^25.2.7
  sqflite: ^2.3.3+1
  path:
  azlistview: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  # assets-generator-begin
  # assets/images/*
    - assets/images/ic_car_models_header1.png
    - assets/images/ic_car_models_header2.png
    - assets/images/ic_index_bar_bubble_gray.png
    - assets/images/ali_connors.png
    - assets/images/banner_bg.jpg
    - assets/images/ic_favorite.png
    - assets/images/avatar.png
  #assets-generator-end
